### ISSUE TITLE
Stylise it better

### ISSUE THREAD

**Issue by aryanmonger20** [aryanmonger20/WebQuiz#1]
Make the results screen better also add some animations

**Comment by r4pt0s** [comment]
Hi,
I can help you out with this one. 
I think would also be great to improve the UI experience for mobile devices. 

Shall I work on this one as well?

**Comment by aryanmonger20** [comment]
Sure !! @r4pt0s

**Comment by r4pt0s** [comment]
Great.
Than you can assign it to me. I'll tackle this one.

Happy coding

**Comment by r4pt0s** [comment]
You need to change the label to **Hacktoberfest ** in order to make your repositories work for hacktoberfest PRs.
Can you change it in your repos?

**Comment by aryanmonger20** [comment]
I already used the Hacktoberfest label,didn't get what you were referring to.

**Comment by r4pt0s** [comment]
You are having a typo in the label
![image](https://user-images.githubusercontent.com/29685827/95000936-826fe700-05c5-11eb-8511-b905ecb301c0.png)

**Comment by aryanmonger20** [comment]
Oh ! Sorry
Thanks  by the way
